-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accessories (
  id bigint NOT NULL DEFAULT nextval('accessories_id_seq'::regclass),
  name text NOT NULL,
  price numeric NOT NULL,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT accessories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inquiries (
  id integer NOT NULL DEFAULT nextval('inquiries_id_seq'::regclass),
  full_name character varying NOT NULL,
  email_address character varying NOT NULL,
  phone character varying,
  company_organization character varying,
  inquiry_type character varying NOT NULL,
  budget character varying,
  message text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  status character varying DEFAULT 'new'::character varying,
  admin_notes text,
  CONSTRAINT inquiries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.installation_schedule (
  id bigint NOT NULL DEFAULT nextval('installation_schedule_id_seq'::regclass),
  order_id bigint NOT NULL,
  scheduled_date date NOT NULL,
  time_slot text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  notes text,
  end_date date,
  end_time_slot character varying,
  CONSTRAINT installation_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT installation_schedule_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.invoice_info (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  invoice_enabled boolean,
  company_name text,
  address text,
  bulstat text,
  mol text,
  mol_custom text,
  order_id bigint NOT NULL,
  CONSTRAINT invoice_info_pkey PRIMARY KEY (id, order_id),
  CONSTRAINT invoice_info_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.order_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  quantity integer,
  service_option text,
  accessories jsonb,
  includes_installation boolean,
  CONSTRAINT order_items_pkey PRIMARY KEY (id, order_id, product_id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.orders (
  order_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name text NOT NULL,
  middle_name text NOT NULL,
  last_name text NOT NULL,
  phone text NOT NULL,
  town text,
  status text,
  modifiedDT timestamp with time zone,
  notes text,
  address text,
  email text,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);
CREATE TABLE public.payment_and_tracking (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'office'::text, 'online'::text, 'mock'::text])),
  session_id uuid DEFAULT gen_random_uuid(),
  order_id bigint NOT NULL,
  total_amount double precision,
  paid_amount double precision,
  CONSTRAINT payment_and_tracking_pkey PRIMARY KEY (id, order_id),
  CONSTRAINT payement_and_tracking_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.products (
  id bigint NOT NULL DEFAULT nextval('products_id_seq'::regclass),
  brand text NOT NULL,
  model text NOT NULL,
  colour text,
  type text,
  capacity_btu integer,
  energy_rating text,
  price numeric NOT NULL,
  previous_price numeric,
  image_url text,
  stock integer DEFAULT 0 CHECK (stock >= 0),
  discount numeric DEFAULT 0 CHECK (discount >= 0::numeric AND discount <= 100::numeric),
  is_archived boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  btu text,
  cop numeric,
  cooling_range text,
  heating_range text,
  eer numeric,
  energy_class text,
  warranty_months integer,
  electricity_cooling_kw numeric,
  electricity_heating_kw numeric,
  room_size_m2 text,
  cooling_power_kw text,
  heating_power_kw text,
  noise_levels_db text,
  manufacturer text,
  made_in text,
  size_indoor text,
  size_outdoor text,
  scop numeric,
  seer numeric,
  ac_type text,
  indoor_unit_type text,
  installment_options text,
  special_offers text,
  class text,
  power_consumption numeric,
  refrigerant_type character varying DEFAULT 'R32'::character varying,
  operating_temp_range character varying,
  noise_level integer,
  air_flow integer,
  warranty_period character varying,
  room_size_recommendation character varying,
  installation_type character varying,
  is_featured boolean DEFAULT false,
  is_bestseller boolean DEFAULT false,
  is_new boolean DEFAULT false,
  description text,
  features jsonb DEFAULT '[]'::jsonb,
  indoor_dimensions character varying,
  outdoor_dimensions character varying,
  indoor_weight numeric,
  outdoor_weight numeric,
  CONSTRAINT products_pkey PRIMARY KEY (id)
);